"""Generate docs/evaluators.md from the registry, so the reference cannot drift.

A hand-maintained list of checks goes stale the first time someone adds one. This
script derives the table from the same objects the evaluation uses, and
`tests/test_docs.py` fails when the committed file no longer matches.
"""

from __future__ import annotations

import sys
from pathlib import Path

from howlproof.evaluators import build_registry
from howlproof.model import Adversary
from howlproof.registry import load_profiles

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "evaluators.md"

HEADER = """# Evaluators

Generated by `scripts/build_evaluator_docs.py` from the registry. Do not edit by
hand; `tests/test_docs.py` fails when this file and the code disagree.

Every evaluator probes the tooling it needs before running, reports
`NOT_APPLICABLE` when the artifact has no such surface, `UNAVAILABLE` when the
tooling is absent, and attaches to each result a statement of what the check does
**not** establish.

"""

ADVERSARY_INTROS = {
    Adversary.FUNCTIONAL: "What input, state or sequence makes this behave incorrectly?",
    Adversary.SECURITY: "Where does the trust boundary not hold, and what can reach across it?",
    Adversary.RELIABILITY: (
        "What happens when a dependency, a restart or the stored state goes wrong?"
    ),
    Adversary.AI: (
        "Can untrusted text become instruction, or malformed output become a trusted value?"
    ),
    Adversary.OPERATOR: (
        "What would a careful person get wrong, and what does the documentation promise "
        "that the code does not do?"
    ),
    Adversary.INTEGRITY: "Did the evaluation itself stay honest?",
}


def render() -> str:
    registry = build_registry()
    profiles = load_profiles()
    membership: dict[str, list[str]] = {}
    for name, data in profiles.items():
        for evaluator_id in data["evaluators"]:
            membership.setdefault(evaluator_id, []).append(name)

    lines = [HEADER.rstrip(), ""]
    for adversary in Adversary:
        members = [e for e in registry.all() if e.adversary is adversary]
        if not members:
            continue
        lines += [
            f"## {adversary.value.title()} adversary",
            "",
            f"*{ADVERSARY_INTROS[adversary]}*",
            "",
            "| Check | Version | What it does | Needs | Profiles |",
            "| --- | --- | --- | --- | --- |",
        ]
        for evaluator in members:
            summary = (evaluator.__doc__ or "").strip().split("\n")[0]
            tools = ", ".join(f"`{name}`" for name in sorted(evaluator.tools)) or "nothing extra"
            in_profiles = ", ".join(sorted(membership.get(evaluator.id, []))) or "none"
            lines.append(
                f"| `{evaluator.id}` | v{evaluator.version} | {summary} | {tools} | "
                f"{in_profiles} |"
            )
        lines.append("")

    lines += [
        "## Profiles",
        "",
        "| Profile | Evaluators | Description |",
        "| --- | --- | --- |",
    ]
    for name, data in sorted(profiles.items()):
        description = " ".join((data.get("description") or "").split())
        lines.append(f"| `{name}` | {len(data['evaluators'])} | {description} |")
    lines += [
        "",
        "A single evaluator id is accepted anywhere a profile name is, so one check can be "
        "re-run in isolation:",
        "",
        "```bash",
        "howlproof evaluate . --profile markup.escaping",
        "```",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    rendered = render()
    if "--check" in sys.argv:
        current = OUTPUT.read_text() if OUTPUT.is_file() else ""
        if current != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date; run this script without --check")
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} matches the registry")
        return 0
    OUTPUT.write_text(rendered)
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
